name: build_and_release

on:
  push:
    tags:
      - "*"
    branches:
        main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            platform: [ proxmoxve ]
    outputs:
      file: ${{  steps.main.outputs.outfile  }}
      version: ${{  steps.main.outputs.version  }}
      tag: ${{  steps.main.outputs.tag  }}
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          path: './work'

      - name: Run build
        id: main
        run: ./work/main.sh ${{ matrix.platform }}

      # - uses: mxschmitt/action-tmate@v3

      - uses: actions/upload-artifact@v4
        with:
          name: ${{  steps.main.outputs.outfile  }}
          path: ./work/${{  steps.main.outputs.outfile  }}
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - run: gh release delete ${{  needs.build.outputs.tag  }} --repo ${{  github.repository  }} --yes || true
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: ncipollo/release-action@v1
        with:
          tag: "${{  needs.build.outputs.tag  }}"
          artifacts: "**/*.xz"
